language: node_js
node_js:
  - stable
addons:
  chrome: stable

after_success:
  - npm install --global coveralls
  - ./node_modules/.bin/nyc report --reporter=text-lcov | coveralls
  - cat coverage/karma-lcov.txt | coveralls
